### ISSUE TITLE
request to add algoexpert code in Java

### ISSUE THREAD

**Issue by NirmalSilwal** [Mayank0255/Coding-Questions#1]
Hi @Mayank0255, will you add the solutions of algoexpert on Java, as you'r code are in Python. 
That would be great help.

Thanks

**Comment by Mayank0255** [comment]
Hi @NirmalSilwal 

Actually this repo is for the questions that I have solved and that's the reason it contains solutions in Python as I solved the questions in Python.

In future if I will be solving it in Java then I would surely mention you

**Comment by NirmalSilwal** [comment]
thanks
